/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Auxiliares.Conexion;
import Auxiliares.Fechas;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Manolo
 */

public class GUI_Empresa extends javax.swing.JFrame {

    private Conexion r_con;
    private final String nombre_BD_Sistema = "BD_Sistema";
    private Fechas control_f = new Fechas();
    private JFrame sesion;
    
    public GUI_Empresa(Conexion con, JFrame s) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        r_con = con;
        sesion = s;
        fieldFechaInicio.setText(control_f.primerDiadelAño());
        fieldFechaFin.setText(control_f.ultimoDiadelAño());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImagen = new javax.swing.JLabel();
        labelAviso = new javax.swing.JLabel();
        fieldRazonSocial = new javax.swing.JTextField();
        fieldFechaInicio = new javax.swing.JFormattedTextField();
        fieldFechaFin = new javax.swing.JFormattedTextField();
        fieldUsuario = new javax.swing.JTextField();
        fieldContrasena = new javax.swing.JTextField();
        buttonCrear = new javax.swing.JButton();
        labelMensaje = new javax.swing.JLabel();
        labelRazonSocial = new javax.swing.JLabel();
        labelFechaInicio = new javax.swing.JLabel();
        labelFechaFin = new javax.swing.JLabel();
        labelAviso2 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        buttonCrear1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empresas del Sistema");
        setIconImage(Toolkit.getDefaultToolkit().getImage("_icono.png"));

        labelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/empresa.png"))); // NOI18N

        labelAviso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelAviso.setForeground(new java.awt.Color(204, 0, 0));
        labelAviso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAviso.setText("<html><div style=\\text-align: center;\\>ATENCIÓN: al completar los datos y confirmar la acción, usted estará creando y registrando una nueva Empresa en el Sistema. Si comprende la responsabilidad que esto conlleva continúe con la operación. Se le solicitara la contraseña de Administrador para evitar accesos indebidos de usuarios. Por cualquier duda consulte el Manual del Sistema.</html>");

        fieldRazonSocial.setToolTipText("");

        try {
            fieldFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fieldFechaInicio.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        try {
            fieldFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fieldFechaFin.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        fieldUsuario.setToolTipText("");

        fieldContrasena.setToolTipText("");
        fieldContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldContrasenaKeyPressed(evt);
            }
        });

        buttonCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        buttonCrear.setText("Crear Empresa");
        buttonCrear.setToolTipText("");
        buttonCrear.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearActionPerformed(evt);
            }
        });
        buttonCrear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonCrearKeyPressed(evt);
            }
        });

        labelMensaje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelMensaje.setForeground(new java.awt.Color(0, 153, 51));
        labelMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensaje.setText(" ");

        labelRazonSocial.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelRazonSocial.setText("Razon Social:");

        labelFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelFechaInicio.setText("Fecha Apertura Ejercicio:");

        labelFechaFin.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelFechaFin.setText("Fecha Cierre Ejercicio:");

        labelAviso2.setForeground(new java.awt.Color(102, 102, 102));
        labelAviso2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAviso2.setText("* Cree un Usuario inicial con privilegio de Administrador para dicha Empresa");

        labelUsuario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelUsuario.setText("Usuario:");

        labelContrasena.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelContrasena.setText("Contraseña:");

        buttonCrear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/arrow-circle-left-2x.png"))); // NOI18N
        buttonCrear1.setText("Salir");
        buttonCrear1.setToolTipText("");
        buttonCrear1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelImagen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                    .addComponent(labelAviso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(labelMensaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(labelRazonSocial)
                        .addGap(18, 18, 18)
                        .addComponent(fieldRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFechaInicio)
                                .addGap(18, 18, 18)
                                .addComponent(fieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(labelFechaFin)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelContrasena)
                                            .addComponent(labelUsuario))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(labelAviso2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCrear1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(labelAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(labelMensaje)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(labelRazonSocial))
                    .addComponent(fieldRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaInicio)
                    .addComponent(fieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaFin)
                    .addComponent(fieldFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(labelAviso2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContrasena))
                .addGap(35, 35, 35)
                .addComponent(buttonCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCrear1)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearActionPerformed
        crearEmpresa ();
    }//GEN-LAST:event_buttonCrearActionPerformed

    private void buttonCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrear1ActionPerformed
        this.dispose();
        sesion.setVisible(true);
    }//GEN-LAST:event_buttonCrear1ActionPerformed

    private void buttonCrearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonCrearKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){    
            crearEmpresa ();
        }
    }//GEN-LAST:event_buttonCrearKeyPressed

    private void fieldContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldContrasenaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){    
            crearEmpresa ();
        }
    }//GEN-LAST:event_fieldContrasenaKeyPressed
    
    private boolean validarCampos (){
        boolean validos = true;
        
        if (fieldRazonSocial.getText().equals("")){
            fieldRazonSocial.requestFocus();
            msj_Error("Ingrese una Razon Social.");
            validos=false;
        }
        else{
            if (!control_f .isFechaValida(fieldFechaInicio.getText())){
                msj_Error("La Fecha de Apertura no es valida.");
                fieldFechaInicio.requestFocus();
                validos=false;
            } 
            else{
                if (!control_f .isFechaValida(fieldFechaFin.getText())){
                    msj_Error("La Fecha de Cierre no es valida.");
                    fieldFechaFin.requestFocus();
                    validos=false;
                }
                else{
                    if (control_f.menorFechas(fieldFechaInicio.getText(), fieldFechaFin.getText())==2){
                            msj_Error("La Fecha de Apertura es mayor a la de Cierre.");
                            fieldFechaInicio.requestFocus();
                            validos=false;
                    }                     
                    else{
                        if (fieldUsuario.getText().equals("")){
                            msj_Error("Ingrese un Usuario Administrador.");
                            fieldUsuario.requestFocus();
                            validos=false;
                        }
                        else{
                            this.vaciarMensaje();
                        }
                    }
                }
            }
        }        
        return validos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCrear;
    private javax.swing.JButton buttonCrear1;
    private javax.swing.JTextField fieldContrasena;
    private javax.swing.JFormattedTextField fieldFechaFin;
    private javax.swing.JFormattedTextField fieldFechaInicio;
    private javax.swing.JTextField fieldRazonSocial;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel labelAviso;
    private javax.swing.JLabel labelAviso2;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelFechaFin;
    private javax.swing.JLabel labelFechaInicio;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JLabel labelRazonSocial;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables

    private void crearEmpresa (){
        if (this.validarCampos()){
            r_con.setBase_datos(nombre_BD_Sistema);
            r_con.abrirConexion();
            if (existeRazonSocial(fieldRazonSocial.getText())){
                this.msj_Error("Razón Social ya Registrada.");
                fieldRazonSocial.requestFocus();
            }
            else{                                       
                try {
                    ResultSet rsl = r_con.Consultar("SELECT * FROM Directorios"); 
                    rsl.next();
                    String directorio = rsl.getString(2);
                    String nuevadatabase = fieldRazonSocial.getText();                        
                    rsl.close();
                    rsl = r_con.Consultar("SELECT COUNT (*) FROM Empresas");
                    rsl.next();
                    String nameinterno = "Empresa_"+(rsl.getInt(1)+1);
                    r_con.Insertar("INSERT INTO Empresas VALUES ('"+nuevadatabase+"',"
                                    + "'"+nameinterno+"');");

                    r_con.crearDatabase_DIR(nameinterno, directorio);
                    //** paso del Sistema a la BD de la empresa
                    r_con.setBase_datos(nameinterno);
                    r_con.cerrarConexion();
                    r_con.abrirConexion();           

                    r_con.executeScripts("SQLQuery_Load_DB_Empresa.sql");
                    r_con.Insertar("INSERT INTO usuario VALUES ('"+
                                    fieldUsuario.getText()+"','Administrador_Inicial',"
                                    + "'Administrador_Inicial','"+
                                    fieldContrasena.getText()+"',1,1);");

                    rsl.close();
                  	
                    String valores = "'"+fieldFechaInicio.getText()+"','"+fieldFechaFin.getText()+"',0,'"+fieldFechaInicio.getText()+"',0,0,0";
                    String sql = "INSERT INTO parametros_contables values ("+valores+");";
                    r_con.Insertar(sql);
                    r_con.cerrarConexion();
                    this.dispose();
                    sesion.setVisible(true);                       
                } catch (SQLException ex) {
                    r_con.cerrarConexion();
                    Logger.getLogger(GUI_Empresa.class.getName()).log(Level.SEVERE, null, ex);
                } finally {            
                    r_con.cerrarConexion();
                }
            }  
        }        
    }
    
    private void vaciarMensaje() {
        labelMensaje.setText(" ");
    }
    
    private void msj_Exito(String msj) {
        labelMensaje.setText(msj);
        labelMensaje.setForeground(new java.awt.Color(0, 153, 51));
    }
    
    private void msj_Error(String msj) {
        labelMensaje.setText(msj);
        labelMensaje.setForeground(Color.RED);
    }

    private boolean existeRazonSocial (String name){
        boolean existe = false;
        try {
            ResultSet rsl = r_con.Consultar("SELECT * FROM Empresas WHERE razon_social = '"+name+"'");
            existe = (rsl.next());
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Empresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        return existe;
    }
}
