/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Colecciones.Usuarios;
import Auxiliares.Conexion;
import Objetos.Perfil;
import Objetos.Usuario;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author GB_Software
 */
public class GUI_Inicio_Sesion extends javax.swing.JFrame {

    private Conexion r_con;
    private Usuario usuario;
    private final String nombre_BD_Sistema = "BD_Sistema";
    private ResultSet rsl;
    
    public GUI_Inicio_Sesion(Conexion con) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        r_con = con;
        r_con.setBase_datos(nombre_BD_Sistema);         
        fieldUsuario.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImagenUsuario = new javax.swing.JLabel();
        fieldUsuario = new javax.swing.JTextField();
        passwordfieldContrasena = new javax.swing.JPasswordField();
        buttonIniciarSesion = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();
        labelMensaje = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesion");
        setIconImage(Toolkit.getDefaultToolkit().getImage("_icono.png"));

        labelImagenUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/u_emp.png"))); // NOI18N

        fieldUsuario.setToolTipText("");

        passwordfieldContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordfieldContrasenaFocusGained(evt);
            }
        });
        passwordfieldContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordfieldContrasenaKeyPressed(evt);
            }
        });

        buttonIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        buttonIniciarSesion.setText("Iniciar Sesión");
        buttonIniciarSesion.setToolTipText("");
        buttonIniciarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIniciarSesionActionPerformed(evt);
            }
        });

        buttonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        buttonSalir.setText("Salir");
        buttonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        labelMensaje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelMensaje.setForeground(new java.awt.Color(0, 153, 51));
        labelMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensaje.setText(" ");

        labelUsuario.setText("Usuario:");

        labelContrasena.setText("Contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelImagenUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelUsuario)
                            .addComponent(labelContrasena))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordfieldContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(fieldUsuario))
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(184, 184, 184))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImagenUsuario)
                .addGap(27, 27, 27)
                .addComponent(labelMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContrasena)
                    .addComponent(passwordfieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(buttonIniciarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSalir)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void buttonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIniciarSesionActionPerformed
        iniciarSesion();
    }//GEN-LAST:event_buttonIniciarSesionActionPerformed

    public void iniciarSesion(){
        if ("".equals(fieldUsuario.getText())){
            msj_usuario_Error("Ingrese un Usuario, por favor.");
            fieldUsuario.requestFocus();
        }
        else{        
            this.vaciarMensaje();            
                try {                                       
                    r_con.abrirConexion();
                    rsl = r_con.Consultar("SELECT * FROM bd_rotiseria.usuario WHERE usr_id = '"+
                                    fieldUsuario.getText()+"' AND usr_contrasenia = '"+
                                    passwordfieldContrasena.getText()+"';");                                                            
                    if (rsl.next()){
                        usuario=new Usuario();
                        usuario.setUsuario(rsl.getString(1));
                        usuario.setNombre(rsl.getString(2));
                        usuario.setApellido(rsl.getString(3));
                        usuario.setContraseña(rsl.getString(4));
                        Perfil perfil=new Perfil();
                        ResultSet rsPerfil=r_con.Consultar("select * from bd_rotiseria.perfil where prf_id="+rsl.getInt(5));
                        rsPerfil.next();
                        perfil.setId(rsPerfil.getInt(1));
                        perfil.setDescripcion(rsPerfil.getString(2));
                        usuario.setPerfil(perfil);
                        usuario.setExiste(rsl.getBoolean(6));
                        if(usuario.getExiste()){
                            GUI_Principal guip=new GUI_Principal(usuario,r_con);
                            guip.setVisible(true);
                            dispose();                      
                        }
                        else{
                            msj_usuario_Error("El usuario esta dado de baja.");
                            fieldUsuario.requestFocus();
                        }
                    }
                    else{
                        msj_usuario_Error("Usuario del Sistema o Contraseña INCORRECTOS.");
                        fieldUsuario.requestFocus();
                    }
                    r_con.cerrarConexion();
                } 
                catch (SQLException ex) {
                    Logger.getLogger(GUI_Inicio_Sesion.class.getName()).log(Level.SEVERE, null, ex);
                }
                finally {
                    r_con.cerrarConexion();
                }            
        }
    }
    
    
    private void passwordfieldContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordfieldContrasenaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
            iniciarSesion();        
    }//GEN-LAST:event_passwordfieldContrasenaKeyPressed

    private void passwordfieldContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfieldContrasenaFocusGained
        // TODO add your handling code here:
        passwordfieldContrasena.setText("");
    }//GEN-LAST:event_passwordfieldContrasenaFocusGained

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonIniciarSesion;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelImagenUsuario;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPasswordField passwordfieldContrasena;
    // End of variables declaration//GEN-END:variables

    private void vaciarMensaje() {
        labelMensaje.setText(" ");
    }
    
    private void msj_usuario_Exito(String msj) {
        labelMensaje.setText(msj);
        labelMensaje.setForeground(new java.awt.Color(0, 153, 51));
    }
    
    private void msj_usuario_Error(String msj) {
        labelMensaje.setText(msj);
        labelMensaje.setForeground(Color.RED);
    }
}
